### ISSUE TITLE
Minor clarifications throughout instructions [BUG]

### ISSUE THREAD

**Issue by MariaEriksson** [carpentries-incubator/blogging-with-hugo-and-github-pages#13]
### Summary

I worked through the tutorial (loved it, thank you 💖) but ran into a minor problem due to using Linux. Another minor point - there were a few lines that were not mentioned in text (and a bit tricky to make out in the video). 

### What needs to be done?
* Hugo with Linux
- [x] Add a note on how to get the most up-to-date version of Hugo on Linux. Instead of downloading Hugo with `sudo apt-get install hugo` in the Terminal, download it via Hugo's release page (and download the newest deb file for Linux). Once downloaded, run`sudo updates` and then `sudo update hugo`.
* Changing the config file
- [x] Add the line `nano config.toml`
* Creating yml file
- [x] Add the line `touch .github/workflows/cd.yml`
- [x] Add the line `nano .github/workflows/cd.yml`
* The tutorial specifies `git add .github/worksflows/cd.yml`, but the line `git add .github` was instead used - does this matter?

### Who can help?
Would be lovely if you have time and capacity to help with this @sgibson91 🌻

**Comment by sgibson91** [comment]
Woohoo! Thank you for opening this @MariaEriksson! 👾 🤖 🍰

**Comment by sgibson91** [comment]
Hi @MariaEriksson! Apologies for how long it took me to get around to addressing this issue 🙏🏻 I have now opened https://github.com/sgibson91/blogging-with-hugo-and-github-pages/pull/18, would you mind reviewing please?

**Comment by sgibson91** [comment]
> * The tutorial specifies `git add .github/worksflows/cd.yml`, but the line `git add .github` was instead used - does this matter?

Technically, no. In terms of best practice, maybe? I'm open to whatever workflows people feel most comfortable with.

`git add .github/worksflows/cd.yml` specifically adds the file `.github/worksflows/cd.yml` to the staging area in `git`, whereas `git add .github` adds _any modified file under the `github` folder_ to the staging area. In this particular case, it's the same thing as there _is_ only one file. However, in more complex projects, you may want to think about what files you add when constructing a commit. This is where personal preference comes in.
